### PR TITLE
Updated package.json

### PR DESCRIPTION
**Pull request by ravenjohn**
Update ownership of the repository to anytv_npmjs

### CODE REVIEW

**Comment by pandafox** [comment]
@FerrielMelarpis / @jkcdarunday please help publish this update

**Comment by jkcdarunday** [comment]
Haro Allen. We do not have write access to the repository. 

Also, the npmjs.com package wasn't published by anytv our account. I think we need to transfer ownership first. 
https://www.npmjs.com/package/cuddle

**Comment by pandafox** [comment]
Well, it looks like it's under https://www.npmjs.com/~anytv_npmjs and @ravenjohn is saying it should be owned by us if commit & publish this change.

**Comment by FerrielMelarpis** [comment]
In that case, we only need write access to this repository to be able to merge these changes.

**Comment by pandafox** [comment]
Done

**Pull request merged**
